AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}
  
  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  {{ cookiecutter.function_name }}:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: {{ cookiecutter.project_name }}/
      Handler: {{ cookiecutter.project_name }}
      Runtime: python3.8
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          KEY1: VALUE
Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  {{ cookiecutter.function_name }}:
    Description: "Lambda Function ARN"
    Value: !GetAtt {{ cookiecutter.function_name }}.Arn
  {{ cookiecutter.function_name }}IamRole:
    Description: "Implicit IAM Role created for {{ cookiecutter.project_name }} function"
    Value: !GetAtt {{ cookiecutter.function_name }}Role.Arn
